CONNECT TO cs421;

DROP TABLE MYTEST01;
DROP TABLE Person;
DROP TABLE Priority;
DROP TABLE Vial;
DROP TABLE Batch;
DROP TABLE Vaccine;
DROP TABLE Nurse;
DROP TABLE Location;
DROP TABLE Schedule; 
DROP TABLE NurseAssigned;
DROP TABLE Slot;
DROP TABLE SlotAllocation;
DROP TABLE Works;

